dailyfresh/dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('df_user.urls',namespace='user')),
    url(r'^goods/', include('df_goods.urls',namespace='goods')),
    url(r'^order/', include('df_order.urls',namespace='order')),
    url(r'^cart/', include('df_cart.urls',namespace='cart')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^search/', include('haystack.urls')),
]

dailyfresh/df_cart/urls.py
from django.conf.urls import url
from . import views
from .views import CartView,CartAddView,CartUpdateView,DeleteCartView


urlpatterns=[
    url(r'^$',CartView.as_view(),name='cart'),
    url(r'^add/$',CartAddView.as_view(),name='add'),  #购物车记录添加
    url(r'^delete/$',DeleteCartView.as_view(),name='delete'),
    url(r'^update/$',CartUpdateView.as_view(),name='update'),
    url(r'^count/$',views.count,name='count'),
]

dailyfresh/df_user/urls.py
from django.conf.urls import url
from . import views
from .views import LoginView,ActiveView,ForgetView,ResetView,EditorView,AddView

urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^register_exist/$',views.register_exist,name='register_exist'),

    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'^forget/$',ForgetView.as_view(),name='forget'),
    url(r'^reset/(.*)$',ResetView.as_view(),name='reset'),

    url(r'^logout_view/$',views.logout_view,name='logout_view'),

    url(r'^active/(?P<token>.*)$',ActiveView.as_view(),name='active'), #用户激活

    url(r'^veridate_code/$',views.veridate_code,name='veridate_code'),
    url(r'^verity/$',views.verity,name='verity'),

    url(r'^info/$',views.info,name='info'),
    url(r'^order/(\d+)/$',views.order,name='order'),
    url(r'^site/$',views.site,name='site'),

    url(r'^address_handler/$',views.address_handler,name='address_handler'),

    url(r'^editor/(\d+)/$',EditorView.as_view(),name='editor'),
    url(r'^delete/(\d+)/$',views.delete,name='delete'),
    url(r'^add/$',AddView.as_view(),name='add'),

    url(r'^area$',views.area,name='area'),
    url(r'^pro/$',views.pro,name='pro'),
    url(r'^city/(\d+)/$',views.city,name='city'),
]

dailyfresh/df_order/models.py
from django.db import models

from db.base_model import BaseModel
class OrderInfo(BaseModel):
    '''订单模型类'''
    PAY_METHODS = {
        '1': "货到付款",
        '2': "微信支付",
        '3': "支付宝",
        '4': '银联支付'
    }
    PAY_METHOD_CHOICES = (
        (1, '货到付款'),
        (2, '微信支付'),
        (3, '支付宝'),
        (4, '银联支付')
    )
    ORDER_STATUS = {
        1: '待支付',
        2: '待发货',
        3: '待收货',
        4: '待评价',
        5: '已完成'
    }
    ORDER_STATUS_CHOICES = (
        (1, '待支付'),
        (2, '待发货'),
        (3, '待收货'),
        (4, '待评价'),
        (5, '已完成')
    )
    order_id = models.CharField(max_length=128, primary_key=True, verbose_name='订单id')
    user = models.ForeignKey('df_user.User', verbose_name='用户')
    addr = models.ForeignKey('df_user.Address', verbose_name='地址')
    pay_method = models.SmallIntegerField(choices=PAY_METHOD_CHOICES, default=3, verbose_name='支付方式')
    total_count = models.IntegerField(default=1, verbose_name='商品数量')
    total_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品总价')
    transit_price = models.DecimalField(max_digits=10, decimal_places=2,verbose_name='订单运费')
    order_status = models.SmallIntegerField(choices=ORDER_STATUS_CHOICES, default=1, verbose_name='订单状态')
    trade_no = models.CharField(max_length=128, verbose_name='支付编号',default='')
    class Meta:
        db_table = 'df_order_info'
        verbose_name = '订单'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.order_id
class OrderGoods(BaseModel):
    '''订单商品模型类'''
    order = models.ForeignKey('OrderInfo', verbose_name='订单')
    sku = models.ForeignKey('df_goods.GoodsSKU', verbose_name='商品SKU')
    count = models.IntegerField(default=1, verbose_name='商品数目')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品价格')
    # comment = models.CharField(max_length=256, verbose_name='评论')
    class Meta:
        db_table = 'df_order_goods'
        verbose_name = '订单商品'
        verbose_name_plural = verbose_name

dailyfresh/df_user/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
from db.base_model import BaseModel

'''
继承AbstractUser:用它的属性
继承BaseModel：共有的属性
'''

class User(AbstractUser,BaseModel):
    '''
    用户模型类
    '''
    class Meta:
        db_table='df_user'
        verbose_name='用户'
        verbose_name_plural=verbose_name


class Address(BaseModel):
    '''地址模型类'''
    username=models.CharField(max_length=30)
    addr=models.CharField(max_length=100)
    postcode=models.CharField(max_length=6)
    phone=models.CharField(max_length=11)
    is_default=models.BooleanField(default=False)
    user=models.ForeignKey(User)

    class Meta:
        db_table='df_address'
        verbose_name='地址'
        verbose_name_plural=verbose_name


class Area(models.Model):
    title=models.CharField(max_length=20)
    parea=models.ForeignKey("self",null=True,blank=True)

    class Meta:
        db_table='df_area'
        verbose_name='省市区'
        verbose_name_plural=verbose_name

dailyfresh/df_user/views.py
from django.shortcuts import render,redirect
from django.core.urlresolvers import reverse
from django.http import JsonResponse,HttpResponse
import hashlib
from .models import *
import random
from  PIL import Image,ImageFont,ImageDraw
from io import BytesIO
from django.views.generic import View
from django.contrib.auth import authenticate,login,logout
from itsdangerous import TimedJSONWebSignatureSerializer as TJSS ,BadSignature,SignatureExpired
from django.core.mail import send_mail
from dailyfresh  import settings
from django.contrib.auth.hashers import make_password
from celery_task.tasks import send_email_task
from django.contrib.auth.decorators import login_required
import re
from redis import StrictRedis
from df_goods.models import *
from df_order.models import *
from django.core.paginator import Paginator



def my_md5(value):
    m=hashlib.md5()
    m.update(value.encode('utf-8'))
    return m.hexdigest()


def register(request):
    if request.method=='GET':
        #注册页面
        return render(request,'df_user/register.html')
    elif request.method=='POST':
        #注册处理
        username = request.POST.get('user_name')
        password = request.POST.get('pwd')
        cpwd = request.POST.get('cpwd')
        email = request.POST.get('email')
        veridate_code = request.POST.get('veridate_code')

        if veridate_code.lower() != request.session.get('veridate_code').lower():
            return redirect(reverse('user:register'))

        # 判断两次密码
        if password != cpwd:
            return redirect(reverse('user:register'))

        # 密码加密
        upwd = my_md5(password)

        # 创建用户
        user=User.objects.create_user(username=username,password=password,email=email)

        #更新
        user.is_active=0
        user.save()

        #加密用户的身份信息，生成激活码
        s=TJSS(settings.SECRET_KEY,3600)
        info={'confirm':user.id}
        token=s.dumps(info).decode()
        url='http://192.168.12.186:8888/user/active/%s'%token

        #发邮件
        subject='天天生鲜欢迎信息'
        message=''  #文本内容
        sender=settings.EMAIL_FROM
        receiver=[email] #收件人
        html_message='<h1>%s,欢迎成为天天生鲜注册会员</h1>请点击下面链接激活你的账户<br/><a href="%s">%s</a>'%(username,url,url)

        send_email_task.delay(subject, message, sender, receiver, html_message)  #发布异步任务

        return render(request,'df_user/active.html')


class ActiveView(View):
    '''用户激活'''
    def get(self,request,token):
        '''进行用户激活'''
        #进行解密，获取要激活的用户的信息
        s=TJSS(settings.SECRET_KEY,3600)
        try:
            info=s.loads(token)
            #获取用户的id
            user_id=info['confirm']

            #根据id获取用户
            user=User.objects.get(id=user_id)
            #更新激活用户
            user.is_active=1
            user.save()
            return redirect('/user/login')
        except SignatureExpired as e:
            #激活链接已过期
            return HttpResponse('激活链接已过期')
        except BadSignature as e:
            return HttpResponse('激活链接非法')

#验证验证码
def verity(request):
    veridate_code=request.GET.get('veridate_code','').lower()
    if veridate_code!=request.session.get('veridate_code').lower( ):
        return JsonResponse({'errmsg':1})
    else:
        return JsonResponse({'errmsg':0})

#判断用户名是否存在
def register_exist(request):
    uname=request.GET.get('uname')
    count=User.objects.filter(username=uname).count()
    return JsonResponse({'count':count})



#类视图
class LoginView(View):
    def get(self,request):
        uname = request.COOKIES.get('uname', '')
        context = {'title': '用户登录', 'error_name': 0, 'error_pwd': 0, 'uname': uname}
        return render(request, 'df_user/login.html', context)

    def post(self,request):
        uname = request.POST.get('username')
        upwd = request.POST.get('pwd')
        remember = request.POST.get('remember')

        user = User.objects.filter(username=uname)

        # 判断用户是否存在
        if user:
            #验证用户
            user1=authenticate(username=uname,password=upwd)
            if user1 is not None:
                if user1.is_active:
                    resp = redirect('/user/info')
                    url = request.GET.get('next')
                    if url:
                        resp = redirect(url)
                    else:
                        resp = redirect('/goods/')

                    # 记住用户名
                    if remember == '1':
                        resp.set_cookie('uname', uname)
                    else:
                        resp.set_cookie('uname', '', 0)
                    #登录成功设置session
                    # request.session['id'] = user[0].id
                    login(request,user1)   #将用户id(_auth_user_id)保存在会话中
                    return resp
                else:
                    return render(request,'df_user/active.html',{'info':'还未激活，无法登录'})
            else:
                context = {'title': '用户登录', 'error_name': 0, 'error_pwd': 1, 'uname': uname, 'upwd': upwd}
                return render(request, 'df_user/login.html', context)
        else:
            context = {'title': '用户登录', 'error_name': 1, 'error_pwd': 0, 'uname': uname, 'upwd': upwd}
            return render(request, 'df_user/login.html', context)


def logout_view(request):
    #删除session
    logout(request)
    return redirect('/user/login/')


class ForgetView(View):
    def get(self,request):
        return render(request,'df_user/forget.html',{'name_err':0,'email_err':0})

    def post(self,request):
        username=request.POST.get('username','')
        email=request.POST.get('email','')
        #获取用户
        user=User.objects.filter(username=username)
        #判断用户是否存在
        if user:
            if user[0].email==email:
                # 加密用户的身份信息，生成激活码
                s = TJSS(settings.SECRET_KEY, 3600)
                info = {'confirm': user[0].id}
                token = s.dumps(info).decode()
                url = 'http://192.168.12.186:8888/user/reset/%s' % token


                subject = '天天生鲜欢迎信息'
                message = ''  # 文本内容
                sender = settings.EMAIL_FROM
                receiver = [email]  # 收件人
                html_message = '<h1>%s</h1>请点击下面链接修改密码<br/><a href="%s">%s</a>' % (username, url, url)
                #发送邮件
                send_email_task.delay(subject, message, sender, receiver, html_message)
                return render(request,'df_user/success.html')
            else:
                return render(request,'df_user/forget.html',{'username':username,'email':email,'name_err':0,'email_err':1})
        else:
            return render(request,'df_user/forget.html',{'username':username,'email':email,'name_err':1,'email_err':0})

class ResetView(View):
    '''重置密码'''
    def get(self, request, token):
        # 进行解密，获取要激活的用户的信息
        s = TJSS(settings.SECRET_KEY, 3600)
        try:
            info = s.loads(token)
            # 获取用户的id
            user_id = info['confirm']
            # 根据id获取用户
            user = User.objects.get(id=user_id)
            return render(request,'df_user/reset.html',{'user':user,'username':user.username})
        except SignatureExpired as e:
            # 激活链接已过期
            return HttpResponse('激活链接已过期')
        except BadSignature as e:
            return HttpResponse('激活链接非法')

    def post(self,request,token):
        username=request.POST.get('username')
        newpwd1=request.POST.get('newpwd1')
        newpwd2=request.POST.get('newpwd2')
        if newpwd1!=newpwd2:
            return render(request,'df_user/reset.html',{'msg':'密码不一致','username':username})
        else:
            #根据id获取用户，重置密码
            user=User.objects.get(id=token)
            user.set_password(newpwd1)
            # user.password=make_password(newpwd1)
            user.save()
            return redirect('/user/login/')

#生成验证码
def veridate_code(request):
    # 定义变量，用于画面的背景色、宽、高
    bgcolor = (random.randrange(20, 100), random.randrange(
        20, 100), 255)
    width = 100
    height = 25
    # 创建画面对象
    im = Image.new('RGB', (width, height), bgcolor)
    # 创建画笔对象
    draw = ImageDraw.Draw(im)
    # 调用画笔的point()函数绘制噪点
    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)
    # 定义验证码的备选值
    str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
    # 随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str1[random.randrange(0, len(str1))]
    # 构造字体对象
    font = ImageFont.truetype('FreeMono.ttf', 23)
    # 构造字体颜色
    fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
    # 绘制4个字
    draw.text((5, 2), rand_str[0], font=font, fill=fontcolor)
    draw.text((25, 2), rand_str[1], font=font, fill=fontcolor)
    draw.text((50, 2), rand_str[2], font=font, fill=fontcolor)
    draw.text((75, 2), rand_str[3], font=font, fill=fontcolor)
    # 释放画笔
    del draw
    #设置session  存在redis中redis服务器必须启动
    request.session['veridate_code']=rand_str

    buf=BytesIO()
    im.save(buf,'png')
    return HttpResponse(buf.getvalue(), 'image/png')

@login_required
def info(request):
    skus = []
    user = request.user
    redis_conn=StrictRedis(host='192.168.12.186',port=6379)
    #判断键是否存在
    if redis_conn.exists('history_%s'%user.id):
        #判断键是否大于4
        if redis_conn.llen('history_%s'%user.id)>=4:
            history=redis_conn.lrange('history_%s'%user.id,0,4)
        else:
            history = redis_conn.lrange('history_%s' % user.id, 0, -1)
        #获取最近浏览的四个商品
        for sku_id in history:
            sku=GoodsSKU.objects.get(id=sku_id)
            skus.append(sku)

    if request.method == 'GET':
        try:
            address = Address.objects.get(user=user, is_default=True)
        except:
            address = None

    context = {'title': '天天生鲜订单页面', 'page_name': 1,'address':address,'page':1,'skus':skus}
    return render(request,'df_user/user_center_info.html',context)

@login_required

dailyfresh/templates/df_user/add.html
{%extends 'df_user/base_center.html'%}
{%block head%}
    <script type="text/javascript">
        $(function () {
            //使用ajax加载省信息
            $.get('/user/pro/',function (data) {
                pro=$('#pro')
                $.each(data.data,function (index,item) {
                    pro.append('<option value="'+item[0]+'">'+item[1]+'</option>')
                })

            })
             //查询市的信息
            $('#pro').change(function () {
                //area110000
                $.get('/user/city/'+$(this).val()+'/',function (list) {
                    city=$('#city')
                    dis=$('#dis')
                    dis.empty().append('<option value="0">请选择区</option>')
                    //{data:[{},{}<{}]}
                    city.empty().append('<option value="0">请选择市</option>')
                    $.each(list.data,function (index,item) {
                        //{a:b,aa:bb} json
                        city.append('<option value="'+item.id+'">'+item.title+'</option>')
                    })
                })
            })

            //查询区的信息
            $('#city').change(function () {
                $.get('/user/city/'+$(this).val()+'/',function (list) {
                    dis=$('#dis')
                    dis.empty().append('<option value="0">请选择区</option>')
                    $.each(list.data,function (index,item) {
                        dis.append('<option value="'+item.id+'">'+item.title+'</option>')
                    })

                })
            })
        })

    </script>
{%endblock head%}


{%block right%}
<div class="right_content clearfix">

				<h3 class="common_title2">新增地址</h3>
				<div class="site_con">
					<form action="/user/add/" method="post">
						{%csrf_token%}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="username" value="">
						</div>
                        <div class="form_group">
                            <label>地址：</label>
                            <select id="pro" name="pro_id">
                                <option value="0">请选择省</option>
                            </select>
                            <select id="city" name="city_id">
                                <option value="0">请选择市</option>
                            </select>
                            <select id="dis" name="dis_id">
                                <option value="0">请选择区</option>
                            </select>
                        </div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="address"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="postcode" value="" maxlength="6" oninput = "value=value.replace(/[^\d]/g,'')">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone" value="" maxlength="11" oninput = "value=value.replace(/[^\d]/g,'')">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
                        <h1 style="font-size: 18px;color: red">{{ info }}</h1>
					</form>
				</div>
		</div>
{%endblock right%}

dailyfresh/templates/df_user/base_center.html
{%extends 'base.html'%}
{%block content%}
<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/" {% if page == 1 %} class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="/user/order/1/" {% if page == 2 %} class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="/user/site/" {% if page == 3 %} class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>

    {%block right%}{%endblock right%}
</div>
{%endblock content%}

dailyfresh/templates/df_user/editor.html
{%extends 'df_user/base_center.html'%}

{%block head%}
    <script type="text/javascript">
        $(function () {
            //使用ajax加载省信息
            $.get('/user/pro/',function (data) {
                pro=$('#pro')
                $.each(data.data,function (index,item) {
                    if(item[0] == {{ pid }}){
                         pro.append('<option value="'+item[0]+'" selected>'+item[1]+'</option>')
                    }else{
                        pro.append('<option value="'+item[0]+'">'+item[1]+'</option>')
                    }

                })

            })

            $.get('/user/city/{{ pid }}/',function (data) {
                city=$('#city')
                $.each(data.data,function (index,item) {
                    if(item.id == {{ cid }}){
                         city.append('<option value="'+item.id+'" selected>'+item.title+'</option>')
                    }else{
                        city.append('<option value="'+item.id+'">'+item.title+'</option>')
                    }

                })

            })

            $.get('/user/city/{{ cid }}/',function (data) {
                dis=$('#dis')
                $.each(data.data,function (index,item) {
                    if(item.id == {{ did }}){
                         dis.append('<option value="'+item.id+'" selected>'+item.title+'</option>')
                    }else{
                        dis.append('<option value="'+item.id+'">'+item.title+'</option>')
                    }

                })

            })


            //查询市的信息
            $('#pro').change(function () {
                //area110000
                $.get('/user/city'+$(this).val()+'/',function (list) {
                    city=$('#city')
                    dis=$('#dis')
                    dis.empty().append('<option value="0">请选择区</option>')
                    //{data:[{},{}<{}]}
                    city.empty().append('<option value="0">请选择市</option>')
                    $.each(list.data,function (index,item) {
                        //{a:b,aa:bb} json
                        city.append('<option value="'+item.id+'">'+item.title+'</option>')
                    })
                })
            })


            //查询区的信息
            $('#city').change(function () {
                $.get('/user/city'+$(this).val()+'/',function (list) {
                    dis=$('#dis')
                    dis.empty().append('<option value="0">请选择区</option>')
                    $.each(list.data,function (index,item) {
                        dis.append('<option value="'+item.id+'">'+item.title+'</option>')
                    })

                })
            })

        })

    </script>

{%endblock head%}


{%block right%}
<div class="right_content clearfix">

				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="/user/editor/{{ address.id }}/" method="post">
						{%csrf_token%}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="username" value="{{address.username}}">
						</div>
                        <div class="form_group">
                            <label>地址：</label>
                            <select id="pro" name="pro_id" >
                                <option value="0">请选择省</option>
                            </select>
                            <select id="city" name="city_id">
                                <option value="0">请选择市</option>
                            </select>
                            <select id="dis" name="dis_id">
                                <option value="0">请选择区</option>
                            </select>
                        </div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="address">{{addrlist.3}}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="postcode" value="{{address.postcode}}" maxlength="6" oninput = "value=value.replace(/[^\d]/g,'')">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone" value="{{address.phone}}" maxlength="11" oninput = "value=value.replace(/[^\d]/g,'')">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
                        <h1 style="font-size: 18px;color: red">{{ info }}</h1>
					</form>
				</div>
		</div>
{%endblock right%}

dailyfresh/templates/df_user/reset.html
{%extends 'base_foot.html'%}

{%block body%}
<div class="login_top clearfix">
		<a href="/goods/" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h2>修改密码</h2>
				</div>
				<div class="form_input">
                <form method="post" action="{%url 'user:reset' user.id%}">
                    {%csrf_token%}

          		        <input type="text" name="username" class="name_input" placeholder="请输入用户名" value="{{username}}">
						<div class="user_error">输入错误</div>
						<input type="password" name="newpwd1" class="pass_input" placeholder="新密码" >
						<div class="pwd_error">输入错误</div>
                        <input type="password" name="newpwd2" class="pass2_input" placeholder="确认新密码" >
						<div class="pwd_error">输入错误</div>
						<input type="submit" name="" value="确认" class="input_submit">
                </form>
                <h1 style="font-size: 18px;color: red">{{ msg }}</h1>
				</div>
			</div>
		</div>
	</div>

{%endblock body%}

dailyfresh/templates/df_user/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>发送邮件成功，请进入邮箱点击链接修改密码</h1>
</body>
</html>

dailyfresh/templates/df_user/user_center_order.html
{%extends 'df_user/base_center.html'%}


{%block head%}
<script>
   $(function () {
       $('.oper_btn').each(function () {
           //获取支付状态
           status=$(this).attr('status')
           if(status == 1){
               $(this).text('去支付')
           }
           else if(status == 4){
               $(this).text('去评价')
           }
           else if(status == 5){
               $(this).text('已完成')
           }
       })


       $('.oper_btn').click(function () {
           //获取status
           status=$(this).attr('status')
           //获取订单id
           order_id=$(this).attr('order_id')
           if(status == 1){
               //进行支付
               csrf=$('input[name="csrfmiddlewaretoken"]').val()
                params={
                'order_id':order_id,
                'csrfmiddlewaretoken':csrf
                 }

                 $.post('/order/pay/',params,function (data) {
                     if(data.res == 3){
                         //引导用户到支付页面
                         window.open(data.pay_url)
                         $.post('/order/check/',params,function (data) {
                             if(data.res == 3){
                                 alert('支付成功')
                                 location.reload()
                             }else{
                                 alert(data.errmsg)
                             }
                         })
                     }else{
                         alert(data.errmsg)
                     }
                 })
           }else if(status == 4){
               // 其他情况
               // 跳转到评价页面
             location.href = '/order/comment/'+order_id
           }
       })
   })
</script>





{%endblock head%}

{%block right%}
    {% csrf_token %}
<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
           {% for order in my_page.object_list %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.create_time }}</li>
					<li class="col02">{{ order.order_id }}</li>
					<li class="col02 stress">{{ order.get_order_status_display }}</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for order_sku in order.order_skus%}
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src="{{ order_sku.sku.image.url }}"></li>
									<li class="col02">{{ order_sku.sku.name }}<em>{{ order_sku.sku.price }}元/{{ order_sku.sku.unite }}</em></li>
									<li class="col03">{{ order_sku.count }}</li>
									<li class="col04">{{ order_sku.amount }}</li>
								</ul>
								{% endfor %}
							</td>
							<td width="15%">{{ order.total_price }}(含运费:{{ order.transit_price }}元)</td>
							<td width="15%">{{ order.get_order_status_display }}</td>
							<td width="15%"><a href="#" class="oper_btn" status="{{ order.order_status  }}" order_id="{{ order.order_id }}">去付款</a></td>
						</tr>
					</tbody>
				</table>
           {% endfor %}

				<div class="pagenation">
                {% if my_page.has_previous %}
                    <a href="/user/order/{{ my_page.previous_page_number  }}">上一页</a>
                {% else %}
                    <a>上一页</a>
                {% endif %}

                {% for page in page_list %}
                    {% if page == my_page.number %}
                        <a class="active">{{ page }}</a>
                    {% else %}
                       <a href="/user/order/{{ page }}">{{ page }}</a>
                    {% endif %}
                {% endfor %}
                {% if my_page.has_next %}
                    <a href="/user/order/{{ my_page.next_page_number }}">下一页</a>
                {% else %}
                    <a>下一页</a>
                {% endif %}
				</div>
		</div>


{%endblock right%}
